package com.example.livewallpaper.desktop

import androidx.compose.runtime.compositionLocalOf
import java.io.InputStreamReader
import java.util.Locale
import java.util.Properties

/**
 * Desktop UI strings loaded from i18n property files.
 *
 * Fields are initialized in the class body instead of a primary constructor so the
 * generated bytecode stays under the JVM 255-parameter method limit.
 */
class DesktopStrings internal constructor(
    private val properties: Properties,
    private val resourcePath: String,
) {
    private fun text(key: String): String = checkNotNull(properties.getProperty(key)) {
        "Missing desktop i18n key '$key' in $resourcePath"
    }

    val appTitle: String = text("appTitle")
    val appVersion: (String) -> String = { text("appVersion").format(it) }
    val images: String = text("images")
    val wallpapers: String = text("wallpapers")
    val aiPaint: String = text("aiPaint")
    val settings: String = text("settings")
    val close: String = text("close")
    val cancel: String = text("cancel")
    val confirm: String = text("confirm")
    val previous: String = text("previous")
    val next: String = text("next")
    val zoomIn: String = text("zoomIn")
    val zoomOut: String = text("zoomOut")
    val fitWindow: String = text("fitWindow")
    val addImages: String = text("addImages")
    val remove: String = text("remove")
    val moveUp: String = text("moveUp")
    val moveDown: String = text("moveDown")
    val multiSelect: String = text("multiSelect")
    val selectAll: String = text("selectAll")
    val cancelSelectAll: String = text("cancelSelectAll")
    val deleteSelected: String = text("deleteSelected")
    val setCurrentWallpaper: String = text("setCurrentWallpaper")
    val startSlideshow: String = text("startSlideshow")
    val stopSlideshow: String = text("stopSlideshow")
    val openWindow: String = text("openWindow")
    val quit: String = text("quit")
    val emptyTitle: String = text("emptyTitle")
    val emptySubtitle: String = text("emptySubtitle")
    val dropImagesHint: String = text("dropImagesHint")
    val wallpaperLibrary: String = text("wallpaperLibrary")
    val createLibrary: String = text("createLibrary")
    val renameLibrary: String = text("renameLibrary")
    val deleteLibrary: String = text("deleteLibrary")
    val deleteLibraryTitle: String = text("deleteLibraryTitle")
    val deleteLibraryMessage: (String) -> String = { name -> text("deleteLibraryMessage").format(name) }
    val libraryNameLabel: String = text("libraryNameLabel")
    val libraryNameHint: String = text("libraryNameHint")
    val addToOtherLibrary: String = text("addToOtherLibrary")
    val addToLibraryTitle: String = text("addToLibraryTitle")
    val noOtherLibraries: String = text("noOtherLibraries")
    val libraryImageCount: (Int) -> String = { count -> text("libraryImageCount").format(count) }
    val cannotDeleteLastLibrary: String = text("cannotDeleteLastLibrary")
    val libraryCount: (Int) -> String = { count -> text("libraryCount").format(count) }
    val backToLibraries: String = text("backToLibraries")
    val setActiveLibrary: String = text("setActiveLibrary")
    val activeLibraryBadge: String = text("activeLibraryBadge")
    val openLibraryHint: String = text("openLibraryHint")
    val openLibrary: String = text("openLibrary")
    val selected: String = text("selected")
    val dragReorderHint: String = text("dragReorderHint")
    val aiPaintTitle: String = text("aiPaintTitle")
    val aiPaintSubtitle: String = text("aiPaintSubtitle")
    val aiPaintComingSoon: String = text("aiPaintComingSoon")
    val paintNewSession: String = text("paintNewSession")
    val paintSessions: String = text("paintSessions")
    val paintNoSessions: String = text("paintNoSessions")
    val paintPromptHint: String = text("paintPromptHint")
    val paintStorageMigrating: String = text("paintStorageMigrating")
    val paintStorageLegacyFallback: String = text("paintStorageLegacyFallback")
    val paintStorageRecoveryRequired: String = text("paintStorageRecoveryRequired")
    val paintApiSettings: String = text("paintApiSettings")
    val paintNoApi: String = text("paintNoApi")
    val paintMissingApi: String = text("paintMissingApi")
    val paintSelectModel: String = text("paintSelectModel")
    val paintSelectRatio: String = text("paintSelectRatio")
    val paintSelectResolution: String = text("paintSelectResolution")
    val paintSend: String = text("paintSend")
    val paintStop: String = text("paintStop")
    val paintInputModeEnterSend: String = text("paintInputModeEnterSend")
    val paintInputModeCtrlEnterSend: String = text("paintInputModeCtrlEnterSend")
    val paintClear: String = text("paintClear")
    val paintAddReferenceImage: String = text("paintAddReferenceImage")
    val paintPinSession: String = text("paintPinSession")
    val paintUnpinSession: String = text("paintUnpinSession")
    val paintRenameSession: String = text("paintRenameSession")
    val paintDeleteSession: String = text("paintDeleteSession")
    val paintRenameSessionTitle: String = text("paintRenameSessionTitle")
    val paintDeleteSessionTitle: String = text("paintDeleteSessionTitle")
    val paintDeleteSessionMessage: String = text("paintDeleteSessionMessage")
    val paintSessionNameLabel: String = text("paintSessionNameLabel")
    val paintGenerating: String = text("paintGenerating")
    val paintFailed: String = text("paintFailed")
    val paintGenerationFailed: String = text("paintGenerationFailed")
    val paintCancelled: String = text("paintCancelled")
    val paintRegenerate: String = text("paintRegenerate")
    val paintDeleteMessage: String = text("paintDeleteMessage")
    val paintCopyMessage: String = text("paintCopyMessage")
    val paintCopied: String = text("paintCopied")
    val paintEditMessage: String = text("paintEditMessage")
    val paintEditUndo: String = text("paintEditUndo")
    val paintEditBrush: String = text("paintEditBrush")
    val paintEditMosaic: String = text("paintEditMosaic")
    val paintEditText: String = text("paintEditText")
    val paintEditCrop: String = text("paintEditCrop")
    val paintEditShapePen: String = text("paintEditShapePen")
    val paintEditShapeRect: String = text("paintEditShapeRect")
    val paintEditShapeOval: String = text("paintEditShapeOval")
    val paintEditShapeArrow: String = text("paintEditShapeArrow")
    val paintEditAddText: String = text("paintEditAddText")
    val paintEditTextTitle: String = text("paintEditTextTitle")
    val paintEditTextHint: String = text("paintEditTextHint")
    val paintStatusDone: String = text("paintStatusDone")
    val paintStatusPending: String = text("paintStatusPending")
    val paintStatusTime: (String, String) -> String = { status, duration ->
        text("paintStatusTime").format(status, duration)
    }
    val paintGeneratingTime: (String) -> String = { duration -> text("paintGeneratingTime").format(duration) }
    val paintDeleteMessageTitle: String = text("paintDeleteMessageTitle")
    val paintDeleteMessageConfirm: String = text("paintDeleteMessageConfirm")
    val paintDeleteVersionHint: String = text("paintDeleteVersionHint")
    val paintDeleteCurrentVersion: String = text("paintDeleteCurrentVersion")
    val paintDeleteAllVersions: String = text("paintDeleteAllVersions")
    val paintVersionLabel: (Int, Int) -> String = { current, total ->
        text("paintVersionLabel").format(current, total)
    }
    val paintCopyPath: String = text("paintCopyPath")
    val paintCopyImage: String = text("paintCopyImage")
    val paintOpenImageLocation: String = text("paintOpenImageLocation")
    val paintSaveAs: String = text("paintSaveAs")
    val paintAddToWallpaper: String = text("paintAddToWallpaper")
    val paintSetWallpaper: String = text("paintSetWallpaper")
    val paintImagePreview: String = text("paintImagePreview")
    val paintImageCompare: String = text("paintImageCompare")
    val paintAddToCompare: String = text("paintAddToCompare")
    val paintRemoveFromCompare: String = text("paintRemoveFromCompare")
    val paintCompareSelectedCount: (Int) -> String = { count -> text("paintCompareSelectedCount").format(count) }
    val paintCompareNeedTwoImages: String = text("paintCompareNeedTwoImages")
    val paintCompareHintHold: String = text("paintCompareHintHold")
    val paintCompareShowingBottom: String = text("paintCompareShowingBottom")
    val imagePreviewRotateLeft: String = text("imagePreviewRotateLeft")
    val imagePreviewRotateRight: String = text("imagePreviewRotateRight")
    val imagePreviewFlipHorizontal: String = text("imagePreviewFlipHorizontal")
    val imagePreviewFlipVertical: String = text("imagePreviewFlipVertical")
    val paintApiConfigList: String = text("paintApiConfigList")
    val paintApiConfigDetail: String = text("paintApiConfigDetail")
    val paintConfigName: String = text("paintConfigName")
    val paintApiBaseUrl: String = text("paintApiBaseUrl")
    val paintAccessToken: String = text("paintAccessToken")
    val paintAuthMode: String = text("paintAuthMode")
    val paintAuthBearer: String = text("paintAuthBearer")
    val paintAuthOfficial: String = text("paintAuthOfficial")
    val paintSave: String = text("paintSave")
    val paintAddConfig: String = text("paintAddConfig")
    val paintUpdate: String = text("paintUpdate")
    val paintDeleteConfig: String = text("paintDeleteConfig")
    val paintNoConfig: String = text("paintNoConfig")
    val paintImportConfig: String = text("paintImportConfig")
    val paintExportConfig: String = text("paintExportConfig")
    val paintConfigImportExport: String = text("paintConfigImportExport")
    val paintExportConfigWarning: String = text("paintExportConfigWarning")
    val paintImportConfigSuccess: (Int) -> String = { count -> text("paintImportConfigSuccess").format(count) }
    val paintExportConfigSuccess: String = text("paintExportConfigSuccess")
    val paintConfigFileError: String = text("paintConfigFileError")
    val paintImportFileTooLarge: String = text("paintImportFileTooLarge")
    val paintImportInvalidJson: String = text("paintImportInvalidJson")
    val paintImportUnsupportedVersion: String = text("paintImportUnsupportedVersion")
    val paintImportInvalidProfile: String = text("paintImportInvalidProfile")
    val paintImportDuplicateProfile: String = text("paintImportDuplicateProfile")
    val paintImportInvalidActiveProfile: String = text("paintImportInvalidActiveProfile")
    val paintJsonFiles: String = text("paintJsonFiles")
    val paintGptSizeAuto: String = text("paintGptSizeAuto")
    val paintGptQualityAuto: String = text("paintGptQualityAuto")
    val paintGptQualityLow: String = text("paintGptQualityLow")
    val paintGptQualityMedium: String = text("paintGptQualityMedium")
    val paintGptQualityHigh: String = text("paintGptQualityHigh")
    val paintGptFormatPng: String = text("paintGptFormatPng")
    val paintGptFormatJpeg: String = text("paintGptFormatJpeg")
    val paintGptFormatWebp: String = text("paintGptFormatWebp")
    val paintEmptyConversationTitle: String = text("paintEmptyConversationTitle")
    val paintEmptyConversationSubtitle: String = text("paintEmptyConversationSubtitle")
    val paintScrollToLatest: String = text("paintScrollToLatest")
    val paintOriginDesktop: String = text("paintOriginDesktop")
    val paintOriginAndroid: String = text("paintOriginAndroid")
    val paintOriginIos: String = text("paintOriginIos")
    val paintOriginUnknown: String = text("paintOriginUnknown")
    val paintStorageSettings: String = text("paintStorageSettings")
    val paintGeneratedImagesDirectory: String = text("paintGeneratedImagesDirectory")
    val paintResponseCacheDirectory: String = text("paintResponseCacheDirectory")
    val paintClipboardCacheDirectory: String = text("paintClipboardCacheDirectory")
    val paintDirectorySize: (String) -> String = { size -> text("paintDirectorySize").format(size) }
    val paintOpenDirectory: String = text("paintOpenDirectory")
    val paintClearCache: String = text("paintClearCache")
    val paintDataBackupSettings: String = text("paintDataBackupSettings")
    val paintDataExport: String = text("paintDataExport")
    val paintDataExportDescription: String = text("paintDataExportDescription")
    val paintDataImport: String = text("paintDataImport")
    val paintDataImportDescription: String = text("paintDataImportDescription")
    val paintDataZipFiles: String = text("paintDataZipFiles")
    val paintDataImportConfirmTitle: String = text("paintDataImportConfirmTitle")
    val paintDataImportConfirmMessage: String = text("paintDataImportConfirmMessage")
    val paintDataImportSelectFile: String = text("paintDataImportSelectFile")
    val paintDataImportSelectFileHint: String = text("paintDataImportSelectFileHint")
    val paintDataImportSelectAnotherFile: String = text("paintDataImportSelectAnotherFile")
    val paintDataImportDropActive: String = text("paintDataImportDropActive")
    val paintDataImportPreviewValidating: String = text("paintDataImportPreviewValidating")
    val paintDataImportPreviewValid: String = text("paintDataImportPreviewValid")
    val paintDataImportPreviewCounts: (Int, Int, Int, Int) -> String = { sessions, messages, drafts, images ->
        text("paintDataImportPreviewCounts").format(sessions, messages, drafts, images)
    }
    val paintDataImportPreviewSource: (String) -> String = { source ->
        text("paintDataImportPreviewSource").format(source)
    }
    val paintDataImportConfirmAction: String = text("paintDataImportConfirmAction")
    val paintDataExporting: String = text("paintDataExporting")
    val paintDataImporting: String = text("paintDataImporting")
    val paintDataExportSuccess: (Int, Int, Int) -> String = { sessions, messages, images ->
        text("paintDataExportSuccess").format(sessions, messages, images)
    }
    val paintDataImportSuccess: (Int, Int, Int) -> String = { sessions, messages, images ->
        text("paintDataImportSuccess").format(sessions, messages, images)
    }
    val paintDataErrorFileAccess: String = text("paintDataErrorFileAccess")
    val paintDataErrorInvalidArchive: String = text("paintDataErrorInvalidArchive")
    val paintDataErrorUnsupportedVersion: String = text("paintDataErrorUnsupportedVersion")
    val paintDataErrorArchiveTooLarge: String = text("paintDataErrorArchiveTooLarge")
    val paintDataErrorUnsafeArchive: String = text("paintDataErrorUnsafeArchive")
    val paintDataErrorMissingImage: String = text("paintDataErrorMissingImage")
    val paintDataErrorCorruptedData: String = text("paintDataErrorCorruptedData")
    val paintDataErrorStorageBusy: String = text("paintDataErrorStorageBusy")
    val paintDataErrorStorageRecoveryRequired: String = text("paintDataErrorStorageRecoveryRequired")
    val paintDataErrorUnknown: String = text("paintDataErrorUnknown")
    val paintGenerationTasks: String = text("paintGenerationTasks")
    val paintGenerationTaskCount: (Int) -> String = { count -> text("paintGenerationTaskCount").format(count) }
    val paintTaskJump: String = text("paintTaskJump")
    val paintTaskCancel: String = text("paintTaskCancel")
    val paintTaskStartedAt: (String) -> String = { time -> text("paintTaskStartedAt").format(time) }
    val paintTaskClearHistory: String = text("paintTaskClearHistory")
    val paintGenerationSuccessNotification: String = text("paintGenerationSuccessNotification")
    val paintGenerationSuccessNotificationDescription: String = text("paintGenerationSuccessNotificationDescription")
    val paintGenerationSuccessTitle: String = text("paintGenerationSuccessTitle")
    val paintGenerationSuccessMessage: (Int) -> String = { count ->
        text("paintGenerationSuccessMessage").format(count)
    }
    val chooseFolder: String = text("chooseFolder")
    val reset: String = text("reset")
    val intervalSeconds: String = text("intervalSeconds")
    val wallpaperSettings: String = text("wallpaperSettings")
    val appearanceSettings: String = text("appearanceSettings")
    val scaleMode: String = text("scaleMode")
    val centerCrop: String = text("centerCrop")
    val fitCenter: String = text("fitCenter")
    val playMode: String = text("playMode")
    val sequential: String = text("sequential")
    val random: String = text("random")
    val theme: String = text("theme")
    val system: String = text("system")
    val light: String = text("light")
    val dark: String = text("dark")
    val stardust: String = text("stardust")
    val clear: String = text("clear")
    val language: String = text("language")
    val followSystem: String = text("followSystem")
    val english: String = text("english")
    val chinese: String = text("chinese")
    val statusIdle: String = text("statusIdle")
    val statusRunning: String = text("statusRunning")
    val statusUnsupported: String = text("statusUnsupported")
    val statusError: String = text("statusError")
    val missingFile: String = text("missingFile")
    val missingBadge: String = text("missingBadge")
    val currentBadge: String = text("currentBadge")
    val desktopBehavior: String = text("desktopBehavior")
    val launchAtStartup: String = text("launchAtStartup")
    val launchAtStartupDescription: String = text("launchAtStartupDescription")
    val restoreSlideshowOnLaunch: String = text("restoreSlideshowOnLaunch")
    val restoreSlideshowOnLaunchDescription: String = text("restoreSlideshowOnLaunchDescription")
    val selectedCount: (Int) -> String = { count -> text("selectedCount").format(count) }
    val multiSelectCount: (Int) -> String = { count -> text("multiSelectCount").format(count) }
    val deleteSelectedTitle: String = text("deleteSelectedTitle")
    val deleteSelectedMessage: (Int) -> String = { count -> text("deleteSelectedMessage").format(count) }
    val currentWallpaper: (String) -> String = { name -> text("currentWallpaper").format(name) }
    val intervalValue: (Int) -> String = { seconds -> text("intervalValue").format(seconds) }
}

val LocalDesktopStrings = compositionLocalOf { desktopStringsFor(null) }

val desktopAppVersion: String = loadDesktopAppVersion()

fun desktopStringsFor(languageTag: String?): DesktopStrings {
    val language = languageTag ?: Locale.getDefault().language
    return if (language.startsWith("zh", ignoreCase = true)) zhCnDesktopStrings else enDesktopStrings
}

private val enDesktopStrings = loadDesktopStrings("i18n/desktop_en.properties")

private val zhCnDesktopStrings = loadDesktopStrings("i18n/desktop_zh_CN.properties")

private fun loadDesktopAppVersion(): String {
    val properties = Properties()
    val stream = checkNotNull(Thread.currentThread().contextClassLoader.getResourceAsStream("app.properties")) {
        "Missing desktop app properties resource"
    }
    stream.use {
        properties.load(InputStreamReader(it, Charsets.UTF_8))
    }
    return checkNotNull(properties.getProperty("version")) {
        "Missing desktop app version"
    }
}

private fun loadDesktopStrings(resourcePath: String): DesktopStrings {
    val properties = Properties()
    val stream = checkNotNull(Thread.currentThread().contextClassLoader.getResourceAsStream(resourcePath)) {
        "Missing desktop i18n resource: $resourcePath"
    }
    stream.use {
        properties.load(InputStreamReader(it, Charsets.UTF_8))
    }
    return DesktopStrings(properties, resourcePath)
}
