package com.example.livewallpaper.desktop

import androidx.compose.runtime.compositionLocalOf
import java.io.InputStreamReader
import java.util.Locale
import java.util.Properties

data class DesktopStrings(
    val appTitle: String,
    val images: String,
    val wallpapers: String,
    val aiPaint: String,
    val settings: String,
    val close: String,
    val cancel: String,
    val previous: String,
    val next: String,
    val zoomIn: String,
    val zoomOut: String,
    val fitWindow: String,
    val addImages: String,
    val remove: String,
    val moveUp: String,
    val moveDown: String,
    val multiSelect: String,
    val selectAll: String,
    val cancelSelectAll: String,
    val deleteSelected: String,
    val setCurrentWallpaper: String,
    val startSlideshow: String,
    val stopSlideshow: String,
    val openWindow: String,
    val quit: String,
    val emptyTitle: String,
    val emptySubtitle: String,
    val dropImagesHint: String,
    val wallpaperLibrary: String,
    val selected: String,
    val dragReorderHint: String,
    val aiPaintTitle: String,
    val aiPaintSubtitle: String,
    val aiPaintComingSoon: String,
    val paintNewSession: String,
    val paintSessions: String,
    val paintNoSessions: String,
    val paintPromptHint: String,
    val paintApiSettings: String,
    val paintNoApi: String,
    val paintMissingApi: String,
    val paintSelectModel: String,
    val paintSelectRatio: String,
    val paintSelectResolution: String,
    val paintSend: String,
    val paintStop: String,
    val paintClear: String,
    val paintAddReferenceImage: String,
    val paintPinSession: String,
    val paintUnpinSession: String,
    val paintRenameSession: String,
    val paintDeleteSession: String,
    val paintRenameSessionTitle: String,
    val paintDeleteSessionTitle: String,
    val paintDeleteSessionMessage: String,
    val paintSessionNameLabel: String,
    val paintGenerating: String,
    val paintFailed: String,
    val paintGenerationFailed: String,
    val paintCancelled: String,
    val paintRegenerate: String,
    val paintDeleteMessage: String,
    val paintCopyMessage: String,
    val paintCopied: String,
    val paintEditMessage: String,
    val paintStatusDone: String,
    val paintStatusPending: String,
    val paintStatusTime: (String, String) -> String,
    val paintGeneratingTime: (String) -> String,
    val paintDeleteMessageTitle: String,
    val paintDeleteMessageConfirm: String,
    val paintDeleteVersionHint: String,
    val paintDeleteCurrentVersion: String,
    val paintDeleteAllVersions: String,
    val paintVersionLabel: (Int, Int) -> String,
    val paintCopyPath: String,
    val paintCopyImage: String,
    val paintOpenImageLocation: String,
    val paintSaveAs: String,
    val paintAddToWallpaper: String,
    val paintSetWallpaper: String,
    val paintImagePreview: String,
    val paintConfigName: String,
    val paintApiBaseUrl: String,
    val paintAccessToken: String,
    val paintAuthMode: String,
    val paintAuthBearer: String,
    val paintAuthOfficial: String,
    val paintSave: String,
    val paintAddConfig: String,
    val paintUpdate: String,
    val paintDeleteConfig: String,
    val paintNoConfig: String,
    val paintGptSizeAuto: String,
    val paintGptQualityAuto: String,
    val paintGptQualityLow: String,
    val paintGptQualityMedium: String,
    val paintGptQualityHigh: String,
    val paintGptFormatPng: String,
    val paintGptFormatJpeg: String,
    val paintGptFormatWebp: String,
    val paintEmptyConversationTitle: String,
    val paintEmptyConversationSubtitle: String,
    val paintScrollToLatest: String,
    val paintStorageSettings: String,
    val paintGeneratedImagesDirectory: String,
    val paintResponseCacheDirectory: String,
    val paintClipboardCacheDirectory: String,
    val paintGenerationSuccessNotification: String,
    val paintGenerationSuccessNotificationDescription: String,
    val paintGenerationSuccessTitle: String,
    val paintGenerationSuccessMessage: (Int) -> String,
    val chooseFolder: String,
    val reset: String,
    val intervalSeconds: String,
    val wallpaperSettings: String,
    val appearanceSettings: String,
    val scaleMode: String,
    val centerCrop: String,
    val fitCenter: String,
    val playMode: String,
    val sequential: String,
    val random: String,
    val theme: String,
    val system: String,
    val light: String,
    val dark: String,
    val stardust: String,
    val clear: String,
    val language: String,
    val followSystem: String,
    val english: String,
    val chinese: String,
    val statusIdle: String,
    val statusRunning: String,
    val statusUnsupported: String,
    val statusError: String,
    val missingFile: String,
    val missingBadge: String,
    val currentBadge: String,
    val desktopBehavior: String,
    val launchAtStartup: String,
    val launchAtStartupDescription: String,
    val restoreSlideshowOnLaunch: String,
    val restoreSlideshowOnLaunchDescription: String,
    val selectedCount: (Int) -> String,
    val multiSelectCount: (Int) -> String,
    val deleteSelectedTitle: String,
    val deleteSelectedMessage: (Int) -> String,
    val currentWallpaper: (String) -> String,
    val intervalValue: (Int) -> String,
)

val LocalDesktopStrings = compositionLocalOf { desktopStringsFor(null) }

fun desktopStringsFor(languageTag: String?): DesktopStrings {
    val language = languageTag ?: Locale.getDefault().language
    return if (language.startsWith("zh", ignoreCase = true)) zhCnDesktopStrings else enDesktopStrings
}

private val enDesktopStrings = loadDesktopStrings("i18n/desktop_en.properties")

private val zhCnDesktopStrings = loadDesktopStrings("i18n/desktop_zh_CN.properties")

private fun loadDesktopStrings(resourcePath: String): DesktopStrings {
    val properties = Properties()
    val stream = checkNotNull(Thread.currentThread().contextClassLoader.getResourceAsStream(resourcePath)) {
        "Missing desktop i18n resource: $resourcePath"
    }
    stream.use {
        properties.load(InputStreamReader(it, Charsets.UTF_8))
    }

    fun text(key: String): String = checkNotNull(properties.getProperty(key)) {
        "Missing desktop i18n key '$key' in $resourcePath"
    }

    return DesktopStrings(
        appTitle = text("appTitle"),
        images = text("images"),
        wallpapers = text("wallpapers"),
        aiPaint = text("aiPaint"),
        settings = text("settings"),
        close = text("close"),
        cancel = text("cancel"),
        previous = text("previous"),
        next = text("next"),
        zoomIn = text("zoomIn"),
        zoomOut = text("zoomOut"),
        fitWindow = text("fitWindow"),
        addImages = text("addImages"),
        remove = text("remove"),
        moveUp = text("moveUp"),
        moveDown = text("moveDown"),
        multiSelect = text("multiSelect"),
        selectAll = text("selectAll"),
        cancelSelectAll = text("cancelSelectAll"),
        deleteSelected = text("deleteSelected"),
        setCurrentWallpaper = text("setCurrentWallpaper"),
        startSlideshow = text("startSlideshow"),
        stopSlideshow = text("stopSlideshow"),
        openWindow = text("openWindow"),
        quit = text("quit"),
        emptyTitle = text("emptyTitle"),
        emptySubtitle = text("emptySubtitle"),
        dropImagesHint = text("dropImagesHint"),
        wallpaperLibrary = text("wallpaperLibrary"),
        selected = text("selected"),
        dragReorderHint = text("dragReorderHint"),
        aiPaintTitle = text("aiPaintTitle"),
        aiPaintSubtitle = text("aiPaintSubtitle"),
        aiPaintComingSoon = text("aiPaintComingSoon"),
        paintNewSession = text("paintNewSession"),
        paintSessions = text("paintSessions"),
        paintNoSessions = text("paintNoSessions"),
        paintPromptHint = text("paintPromptHint"),
        paintApiSettings = text("paintApiSettings"),
        paintNoApi = text("paintNoApi"),
        paintMissingApi = text("paintMissingApi"),
        paintSelectModel = text("paintSelectModel"),
        paintSelectRatio = text("paintSelectRatio"),
        paintSelectResolution = text("paintSelectResolution"),
        paintSend = text("paintSend"),
        paintStop = text("paintStop"),
        paintClear = text("paintClear"),
        paintAddReferenceImage = text("paintAddReferenceImage"),
        paintPinSession = text("paintPinSession"),
        paintUnpinSession = text("paintUnpinSession"),
        paintRenameSession = text("paintRenameSession"),
        paintDeleteSession = text("paintDeleteSession"),
        paintRenameSessionTitle = text("paintRenameSessionTitle"),
        paintDeleteSessionTitle = text("paintDeleteSessionTitle"),
        paintDeleteSessionMessage = text("paintDeleteSessionMessage"),
        paintSessionNameLabel = text("paintSessionNameLabel"),
        paintGenerating = text("paintGenerating"),
        paintFailed = text("paintFailed"),
        paintGenerationFailed = text("paintGenerationFailed"),
        paintCancelled = text("paintCancelled"),
        paintRegenerate = text("paintRegenerate"),
        paintDeleteMessage = text("paintDeleteMessage"),
        paintCopyMessage = text("paintCopyMessage"),
        paintCopied = text("paintCopied"),
        paintEditMessage = text("paintEditMessage"),
        paintStatusDone = text("paintStatusDone"),
        paintStatusPending = text("paintStatusPending"),
        paintStatusTime = { status, duration -> text("paintStatusTime").format(status, duration) },
        paintGeneratingTime = { duration -> text("paintGeneratingTime").format(duration) },
        paintDeleteMessageTitle = text("paintDeleteMessageTitle"),
        paintDeleteMessageConfirm = text("paintDeleteMessageConfirm"),
        paintDeleteVersionHint = text("paintDeleteVersionHint"),
        paintDeleteCurrentVersion = text("paintDeleteCurrentVersion"),
        paintDeleteAllVersions = text("paintDeleteAllVersions"),
        paintVersionLabel = { current, total -> text("paintVersionLabel").format(current, total) },
        paintCopyPath = text("paintCopyPath"),
        paintCopyImage = text("paintCopyImage"),
        paintOpenImageLocation = text("paintOpenImageLocation"),
        paintSaveAs = text("paintSaveAs"),
        paintAddToWallpaper = text("paintAddToWallpaper"),
        paintSetWallpaper = text("paintSetWallpaper"),
        paintImagePreview = text("paintImagePreview"),
        paintConfigName = text("paintConfigName"),
        paintApiBaseUrl = text("paintApiBaseUrl"),
        paintAccessToken = text("paintAccessToken"),
        paintAuthMode = text("paintAuthMode"),
        paintAuthBearer = text("paintAuthBearer"),
        paintAuthOfficial = text("paintAuthOfficial"),
        paintSave = text("paintSave"),
        paintAddConfig = text("paintAddConfig"),
        paintUpdate = text("paintUpdate"),
        paintDeleteConfig = text("paintDeleteConfig"),
        paintNoConfig = text("paintNoConfig"),
        paintGptSizeAuto = text("paintGptSizeAuto"),
        paintGptQualityAuto = text("paintGptQualityAuto"),
        paintGptQualityLow = text("paintGptQualityLow"),
        paintGptQualityMedium = text("paintGptQualityMedium"),
        paintGptQualityHigh = text("paintGptQualityHigh"),
        paintGptFormatPng = text("paintGptFormatPng"),
        paintGptFormatJpeg = text("paintGptFormatJpeg"),
        paintGptFormatWebp = text("paintGptFormatWebp"),
        paintEmptyConversationTitle = text("paintEmptyConversationTitle"),
        paintEmptyConversationSubtitle = text("paintEmptyConversationSubtitle"),
        paintScrollToLatest = text("paintScrollToLatest"),
        paintStorageSettings = text("paintStorageSettings"),
        paintGeneratedImagesDirectory = text("paintGeneratedImagesDirectory"),
        paintResponseCacheDirectory = text("paintResponseCacheDirectory"),
        paintClipboardCacheDirectory = text("paintClipboardCacheDirectory"),
        paintGenerationSuccessNotification = text("paintGenerationSuccessNotification"),
        paintGenerationSuccessNotificationDescription = text("paintGenerationSuccessNotificationDescription"),
        paintGenerationSuccessTitle = text("paintGenerationSuccessTitle"),
        paintGenerationSuccessMessage = { count -> text("paintGenerationSuccessMessage").format(count) },
        chooseFolder = text("chooseFolder"),
        reset = text("reset"),
        intervalSeconds = text("intervalSeconds"),
        wallpaperSettings = text("wallpaperSettings"),
        appearanceSettings = text("appearanceSettings"),
        scaleMode = text("scaleMode"),
        centerCrop = text("centerCrop"),
        fitCenter = text("fitCenter"),
        playMode = text("playMode"),
        sequential = text("sequential"),
        random = text("random"),
        theme = text("theme"),
        system = text("system"),
        light = text("light"),
        dark = text("dark"),
        stardust = text("stardust"),
        clear = text("clear"),
        language = text("language"),
        followSystem = text("followSystem"),
        english = text("english"),
        chinese = text("chinese"),
        statusIdle = text("statusIdle"),
        statusRunning = text("statusRunning"),
        statusUnsupported = text("statusUnsupported"),
        statusError = text("statusError"),
        missingFile = text("missingFile"),
        missingBadge = text("missingBadge"),
        currentBadge = text("currentBadge"),
        desktopBehavior = text("desktopBehavior"),
        launchAtStartup = text("launchAtStartup"),
        launchAtStartupDescription = text("launchAtStartupDescription"),
        restoreSlideshowOnLaunch = text("restoreSlideshowOnLaunch"),
        restoreSlideshowOnLaunchDescription = text("restoreSlideshowOnLaunchDescription"),
        selectedCount = { count -> text("selectedCount").format(count) },
        multiSelectCount = { count -> text("multiSelectCount").format(count) },
        deleteSelectedTitle = text("deleteSelectedTitle"),
        deleteSelectedMessage = { count -> text("deleteSelectedMessage").format(count) },
        currentWallpaper = { name -> text("currentWallpaper").format(name) },
        intervalValue = { seconds -> text("intervalValue").format(seconds) },
    )
}
